export {
  SET_BUILDER: "SET_BUILDER",
  CHANGE_PIZZA_NAME: "SET_PIZZA_NAME",
  CHANGE_DOUGH: "CHANGE_DOUGH",
  CHANGE_SOUSE: "CHANGE_SOUSE",
  CHANGE_SIZE: "CHANGE_SIZE",
  CONTINUOUS_INGREDIENTS: "CONTINUOUS_INGREDIENTS",
  MOVE_INGREDIENTS: "MOVE_INGREDIENTS",
};
