export const SET_BUILDER = "SET_BUILDER";
export const COUNT_INGREDIENT = "COUNT_INGREDIENT";
export const MOVE_INGREDIENT = "MOVE_INGREDIENT";
export const CHANGE_OPTIONS = "CHANGE_OPTIONS";
export const INPUT_SET_NAME = "INPUT_SET_NAME";
